version: '3.8'

services:
  db:
    image: postgres:14 
    ports:
      - "${POSTGRES_PORT}:5432"  # Map the port using the .env variable
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - accusaga_network

  backend:
    build:
      context: ./
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"
    command: ./wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8000
    networks:
      - accusaga_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    networks:
      - accusaga_network

networks:
  accusaga_network:
    driver: bridge


